name: openvla-interp
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - tqdm
  - pyyaml
  - imageio
  - pillow
  - scikit-learn
  - pytorch=2.2.0
  - pytorch-cuda=12.1
  - torchvision=0.17.0
  - torchaudio=2.2.0
  - pip:
      - transformers==4.40.1
      - tokenizers==0.19.1
      - timm>=0.9.10,<1.0.0
      - accelerate
      - huggingface_hub
      - libero
      - robosuite==1.4.0
      - imageio[ffmpeg]
      - bddl==1.0.1
      - easydict==1.9
      - cloudpickle==2.1.0
      - gym==0.25.2
      - mujoco
